---
- name: cp2-role | tasks | acr_images.yml | ACR login
  containers.podman.podman_login:
    username: "{{ acr_user }}"
    password: "{{ acr_pass }}"
    registry: "{{ acr_registry }}"

- name: cp2-role | tasks | acr_images.yml | Download images
  containers.podman.podman_image:
    name: "{{ item.image_path }}"
    tag: "{{ item.tag }}"
    state: present
    pull: yes
  loop: "{{ images }}"
  when: item.pull == true

- name: cp2-role | tasks | acr_images.yml | Tag images
  containers.podman.podman_tag:
    image: "{{ item.image_path }}:{{ item.tag }}"
    target_names: "{{ acr_registry }}/{{ item.folder }}/{{ item.name }}:casopractico2"
  loop: "{{ images }}"

- name: cp2-role | tasks | acr_images.yml | Push images into ACR
  containers.podman.podman_image:
    name: "{{ acr_registry }}/{{ item.folder }}/{{ item.name }}:casopractico2"
    push: true
    validate_certs: false
  loop: "{{ images }}"
...