---
- name: cp2-role | tasks | launch_webserver.yml | ACR login
  containers.podman.podman_login:
    username: "{{ acr_user }}"
    password: "{{ acr_pass }}"
    registry: "{{ acr_registry }}"

- name: cp2-role | tasks | launch_webserver.yml | Execute nginx container
  containers.podman.podman_container:
    name: webserver
    image: "{{ acr_registry }}/{{ podman_nginx_folder }}/{{ podman_nginx_image }}:casopractico2"
    state: started
    ports:
      - "80:80"
      - "443:443"
...