---
- name: cp2-role | tasks | prepare_vm.yml | Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: cp2-role | tasks | prepare_vm.yml | Install Podman
  ansible.builtin.apt:
    name: podman
    update_cache: true
    state: present

- name: cp2-role | tasks | prepare_vm.yml | Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: cp2-role | tasks | prepare_vm.yml | Install passlib
  ansible.builtin.pip:
    name: passlib
    state: present
...