---
- name: cp2-role | tasks | acr_images.yml | Login acr
  containers.podman.podman_login:
    username: "{{ acr_user }}"
    password: "{{ acr_pass }}"
    registry: "{{ acr_registry }}"

- name: cp2-role | tasks | acr_images.yml | Descargar imágenes desde Docker Hub (repositorio público)
  containers.podman.podman_image:
    name: "docker.io/library/nginx"
    tag: "latest"
    state: present
    pull: yes

- name: cp2-role | tasks | acr_images.yml | Etiquetar imágenes descargadas para ACR
  containers.podman.podman_tag:
    image: "docker.io/library/nginx:latest"
    target_names: "{{ acr_registry }}/nginx:casopractico2"

- name: cp2-role | tasks | acr_images.yml | Subir imágenes a ACR
  containers.podman.podman_image:
    name: "{{ acr_registry }}/nginx:casopractico2"
    push: true
    validate_certs: false
...