---
- name: playbook.yml | Run cp2-role
  hosts: cp2-vm
  become: true
  vars_files:
    - secrets.yml
  tasks:
    - name: playbook.yml | Include cp2-role role
      ansible.builtin.include_role:
        name: cp2-role

- name: playbook.yml | Run app_deployment_role
  hosts: localhost
  vars_files:
    - secrets.yml
  tasks:
    - name: playbook.yml | Include app_deployment_role role
      ansible.builtin.include_role:
        name: app_deployment_role
...