---
- name: playbook.yml | Run cp2 Role
  hosts: cp2-vm
  become: true
  vars_files:
    - secrets.yml
  tasks:
    - name: playbook.yml | Include role
      ansible.builtin.include_role:
        name: cp2-role
...
 # buscar imagen de azure-vote-front
 # crear fichero .kube/config